/**
 * Copyright (c) 2013 SAP
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the SAP nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL SAP BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.sopeco.webui.server.helper;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

import javax.servlet.ServletContext;

import com.google.gwt.core.shared.GWT;

/**
 * 
 * @author Marius Oehler
 * 
 */
public final class MavenInfos {

	private static final String POM_PATH = "META-INF/maven/";
	private static final String POM_NAME = "pom.properties";

	private MavenInfos() {
	}

	private static String version;
	private static String buildDate;
	private static boolean loaded = false;
	private static boolean pomFound = false;

	/**
	 * Reads the build version and date from the pom.proterties, which is
	 * generated by the maven build process.
	 * 
	 * @param context
	 *            context of the servlet, which is required to find the correct
	 *            path.
	 */
	private static void load(ServletContext context) {
		if (loaded) {
			return;
		}

		File pomFile = search(new File(context.getRealPath(POM_PATH)));

		if (pomFile != null) {
			pomFound = true;

			try {
				BufferedReader reader = new BufferedReader(new FileReader(pomFile));

				reader.readLine();
				buildDate = reader.readLine().substring(1);

				String line;
				while ((line = reader.readLine()) != null) {
					String[] split = line.split("=");
					if (split[0].equals("version")) {
						version = split[1];
						break;
					}
				}

				reader.close();
			} catch (FileNotFoundException e) {
				GWT.log("No maven build information found.");
			} catch (IOException e) {
				e.printStackTrace();
			}

		}
		loaded = true;
	}

	/**
	 * Searchs the pom.proteries file in the given directory.
	 * 
	 * @param dir
	 * @return
	 */
	private static File search(File dir) {
		if (!dir.exists()) {
			return null;
		}
		File[] files = dir.listFiles();
		for (int i = 0; i < files.length; i++) {
			File f = files[i];
			if (!f.isDirectory() && f.getName().equals(POM_NAME)) {
				return f;
			}
			if (f.isDirectory()) {
				File temp = search(f);
				if (temp != null) {
					return temp;
				}
			}
		}
		return null;
	}

	/**
	 * Returns a string which contains the build version and build date. If no
	 * build information are available, the return value is an empty string.
	 * 
	 * @param context
	 * @return
	 */
	public static String getInfoString(ServletContext context) {
		load(context);
		if (pomFound) {
			return version + " - " + buildDate;
		} else {
			return "asd";
		}
	}
}
